quarkus:
  http:
    cors:
      enabled: true
      origins: "*"
    port: 1234
    access-log:
      enabled: true
      log-to-file: false
  virtual-threads:
    enabled: true
  hibernate-orm:
    database:
      start-offline: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${JDBC_STRING}
  oidc:
    application-type: service
    auth-server-url: ${KEYCLOAK_URL}
  minio:
    host: ${S3_HOST}
    port: ${S3_PORT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    secure: ${S3_SECURE}
    region: ${S3_REGION}
    force-path-style: true
    bucket-name: metatrack
  smallrye-openapi:
    path: /openapi
    always-include: true
metatrack:
  webhook:
    minio-secret: ${MINIO_SECRET_KEY}
  file:
    presign-expiry-seconds: 600
taxon-api/mp-rest/url: ${TAXON_API_URL:http://localhost:8080}
