
ALTER TABLE sample ADD COLUMN project_title VARCHAR(255);
ALTER TABLE sample ADD COLUMN description VARCHAR(255);
ALTER TABLE sample ADD COLUMN isolate VARCHAR(255);
ALTER TABLE sample ADD COLUMN collected_by VARCHAR(255);
ALTER TABLE sample ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE sample ADD COLUMN longitude DOUBLE PRECISION;
ALTER TABLE sample ADD COLUMN environmental_sample VARCHAR(255);
ALTER TABLE sample ADD COLUMN host_associated VARCHAR(255);
ALTER TABLE sample ADD COLUMN host_common_name VARCHAR(255);
ALTER TABLE sample ADD COLUMN host_subject_id VARCHAR(255);
ALTER TABLE sample ADD COLUMN collector_name VARCHAR(255);
ALTER TABLE sample ADD COLUMN collecting_institution VARCHAR(255);
ALTER TABLE sample ADD COLUMN host_sex VARCHAR(255);
ALTER TABLE sample ADD COLUMN influenza_test_method VARCHAR(255);
ALTER TABLE sample ADD COLUMN influenza_test_result VARCHAR(255);
ALTER TABLE sample ADD COLUMN other_pathogens_tested VARCHAR(255);
ALTER TABLE sample ADD COLUMN other_pathogens_test_result VARCHAR(255);
ALTER TABLE sample ADD COLUMN host_habitat VARCHAR(255);
ALTER TABLE sample ADD COLUMN isolation_source_host_associated VARCHAR(255);
ALTER TABLE sample ADD COLUMN host_behaviour VARCHAR(255);
ALTER TABLE sample ADD COLUMN isolation_source_non_host_associated VARCHAR(255);
ALTER TABLE sample ADD COLUMN influenza_virus_type VARCHAR(255);
ALTER TABLE sample ADD COLUMN influenza_sub_type VARCHAR(255);
ALTER TABLE sample ADD COLUMN serovar VARCHAR(255);
ALTER TABLE sample ADD COLUMN strain VARCHAR(255);
ALTER TABLE sample ADD COLUMN host_age VARCHAR(255);
ALTER TABLE sample ADD COLUMN county VARCHAR(255);
ALTER TABLE sample ADD COLUMN commune VARCHAR(255);
ALTER TABLE sample ADD COLUMN hospital_health_institution VARCHAR(255);
