create sequence file_seq start with 1 increment by 50;
create sequence project_member_seq start with 1 increment by 50;
create sequence project_seq start with 1 increment by 50;
create table file (id bigint not null, sample_id uuid, uuid uuid not null unique, file_name varchar(255) not null, object_key varchar(255) not null unique, status varchar(255) check ((status in ('PENDING','UPLOADED'))), virtual_path varchar(255) not null unique, primary key (id));
create table project (created_on timestamp(6) with time zone, id bigint not null, modified_on timestamp(6) with time zone, owner uuid not null, description varchar(255), name varchar(255) not null unique, primary key (id));
create table project_member (id bigint not null, project_id bigint not null, member_id uuid not null, role varchar(255) not null check ((role in ('OWNER','ADMIN','EDITOR','VIEWER'))), primary key (id), unique (member_id, project_id));
create table sample (collection_date date, host_tax_id integer not null, tax_id integer not null, created_on timestamp(6) with time zone, modified_on timestamp(6) with time zone, project_id bigint, id uuid not null, alias varchar(255), host_health_state varchar(255), institution varchar(255), isolation_source varchar(255), location varchar(255), mlst varchar(255), name varchar(255), sequencing_lab varchar(255), primary key (id), unique (name, project_id));
alter table if exists file add constraint FKe38dhse49y7t0xdvrbwo2rh5d foreign key (sample_id) references sample;
alter table if exists project_member add constraint FK103dwxad12nbaxtmnwus4eft2 foreign key (project_id) references project;
alter table if exists sample add constraint FKeytsctv5b8stbijub6yeil5ie foreign key (project_id) references project;
